<?xml version="1.0" encoding="utf-8"?><Database Name="AET2021" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.1.131\DATASRV;Initial Catalog=AET2021;Persist Security Info=True;User ID=RAPORLAMA" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AET" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_WEB_SATIS_RAPOR_USERS" Member="TBL_WEB_SATIS_RAPOR_USERs">
    <Type Name="TBL_WEB_SATIS_RAPOR_USER">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>